### ISSUE TITLE
movies already requested dont show as requested

### ISSUE THREAD

**Issue by dejected1** [ak-rex/Requested-for-Ombi#1]
Ombi v3.0.3185
Radarr v0.2.0.1067
Android 8.1.0
Requested 1.42

When searching for a movie that is already in Radarr (but not yet downloaded), it doesn't show as requested and lets you request it again. The web interface for Ombi does shows this status correctly. 

This is the only thing preventing me from using this app, as i don't want to receive requests for duplicates. 

This status is reflected correctly in a TV search by the way. (with sonarr and and tv shows already in my list by not yet downloaded)

**Comment by ak-rex** [comment]
I'll take a look at it after work tomorrow. Thanks for the input, hope it's a easy fix.

**Comment by ak-rex** [comment]
Issue has been resolved in version 1.44. thanks for letting me know.
