### ISSUE TITLE
Tv Shows Request are blank/null

### ISSUE THREAD

**Issue by Lockszmith-GH** [ak-rex/Requested-for-Ombi#7]
TV Shows Request page isn't working properly
While Movies page renders correctly.

If this is something to for with my Ombi setup, then what is different about the TV request to the movies one?

Ombi ver 3.0.3922-develop
Requested for Ombi 1.67
Running on Android 9 (Build: ONEPLUS A6003_22_180915)

Ombi is running behind an nginx+letse crypt https reverse proxy

**Comment by ak-rex** [comment]
I've been busy for the last few weeks. it looks like there was a recent change in Ombi, I'll address the issue tonight thanks for bringing it to my attention.

**Comment by ak-rex** [comment]
Fix available in Requested 1.68
